name: snakemake-example
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gitpython=3.1.31
  - ipython=8.13.2
  - jinja2=3.1.2
  - networkx=3.1
  - pygments=2.15.1
  - pygraphviz=1.10
  - python=3.11.3
  - python-wget=3.2
  - snakemake-minimal=7.25.3
